# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-16 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
                ('e_mail', models.EmailField(max_length=128)),
                ('grade', models.CharField(default='Citizen', max_length=120)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
