# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('angus', '0002_auto_20160818_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('BR', 'Bronze'), ('SL', 'Silver'), ('GL', 'Gold'), ('PL', 'Platinum'), ('DI', 'Diamond'), ('MA', 'Master'), ('CH', 'Challenger')], default='BR', max_length=120)),
                ('picture', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
