# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angus', '0003_auto_20160819_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.CharField(default='Visitor', max_length=120)),
                ('pub_date', models.DateTimeField(verbose_name='datetime')),
                ('mod_date', models.DateTimeField(verbose_name='datetime')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
