# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('angus', '0004_guestbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 5, 21, 17, 583529, tzinfo=utc), verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 5, 21, 17, 583258, tzinfo=utc), verbose_name='datetime'),
        ),
    ]
